name: expense_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gsheets: ^0.5.0
  flutter_dotenv: ^5.2.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  analyzer: ^5.13.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  expense_core:
    path: ../expense-core 
  flutter_modular: ^6.3.4
  dio:
  get: ^4.7.2
  get_storage: ^2.1.1
  lottie: ^3.3.1
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
    - family: Archivo
      fonts:
        - asset: fonts/Archivo-Regular.ttf
          weight: 400
        - asset: fonts/Archivo-Medium.ttf
          weight: 500
        - asset: fonts/Archivo-SemiBold.ttf
          weight: 600
        - asset: fonts/Archivo-Bold.ttf
          weight: 700
    - family: Items
      fonts:
        - asset: fonts/Items-CondensedLight2.otf
          weight: 300
        - asset: fonts/Items-CondensedLight.otf
          weight: 300
        - asset: fonts/Items-CondensedLightItalic.otf
          weight: 300
        - asset: fonts/Items-CondensedLightItalic2.otf
          weight: 300  


